# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # prénom, first name
  - regex: ":(pr|fi)"
    label: "Guillaume"
    replace: "Guillaume"

  # nom, last name
  - regex: ":(no|la)"
    label: "Malek"
    replace: "Malek"

  # name
  - regex: ":(na)"
    label: "Guillaume Malek"
    replace: "Guillaume Malek"

  # tva intracommunautaire
  - regex: ":(tv)"
    label: "FR67942722422"
    replace: "FR67942722422"

  # siret, Paris MAJ
  - regex: ":(siret)"
    label: "94272242200014"
    replace: "94272242200014"

  # siren
  - regex: ":(siren)"
    label: "942722422"
    replace: "942722422"

  # mail, email
  - regex: ":(ma|em)"
    label: "guillaume.malek98@gmail.com"
    replace: "guillaume.malek98@gmail.com"

  # mail pro, pro mail
  - regex: ":(mp|pm)"
    label: "guillaume.malek.pro@gmail.com"
    replace: "guillaume.malek.pro@gmail.com"

  # adresse, address
  - regex: ":(adr|addr|address)"
    label: "21 rue Christophe Thomas Walliser 67200 Strasbourg"
    replace: "21 rue Christophe Thomas Walliser 67200 Strasbourg"

  # ville, city
  - regex: ":(vi|ci)"
    label: "Strasbourg"
    replace: "Strasbourg"

  # code postal, postal code, zip code
  - regex: ":(co|cp|zi|po)"
    label: "67200"
    replace: "67200"

  # rue, street
  - regex: ":(ru|stre)"
    label: "21 rue Christophe Thomas Walliser"
    replace: "21 rue Christophe Thomas Walliser"

  # téléphone, phone
  - regex: ":(tel|ph)"
    label: "0787524370"
    replace: "0787524370"

  # thumbs up and down
  - trigger: ":tu"
    label: "👍"
    replace: "👍"
  - trigger: ":td"
    label: "👎"
    replace: "👎"

  # NOTE: espanso uses YAML to define matches, so pay attention to the indentation!

  # But matches can also be dynamic:

  # Print the current date
  - trigger: ":da"
    replace: "{{"{{today}}"}}"
    vars:
      - name: today
        type: date
        params:
          format: "%d/%m/%Y"

  # Print the output of a shell command
  - trigger: ":sh"
    replace: "{{"{{output}}"}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

# And much more! For more information, visit the docs: https://espanso.org/docs/
